// Central strings — English source of truth with locale overlays.
// Keep user-facing UI copy here so language changes can affect every screen.

export type Language = 'en' | 'ru' | 'ky' | 'zh' | 'ar' | 'de';

export const enStrings = {
  // ── Splash & Language Select (screen 01) ─────────────────
  splash: {
    wordmark: 'Tabylga',
    tagline: 'Your Kyrgyzstan, one tap away',
    taglineSub: 'Find · Планируй · Табыл',
    languageSheetTitle: 'Choose your language',
    continueButton: 'Continue',
  },

  // ── Welcome Carousel (screen 02) ─────────────────────────
  welcome: {
    skip: 'Skip',
    next: 'Next',
    getStarted: 'Get Started',
    slide1: {
      title: 'Plan with AI, or plan yourself.',
      body: 'Generate a full multi-day trip from a sentence, or book each hotel, taxi and guide on your own — it\'s all in one place.',
    },
    slide2: {
      title: 'One wallet for everything.',
      body: 'Top up once with Visa, MBank, UnionPay or Apple Pay. Pay every yurt camp, guide and restaurant without touching cash.',
    },
    slide3: {
      title: 'Works even offline in the mountains.',
      body: 'No signal? No problem. Pay yurt hosts on Song-Kul with your signed offline token. It syncs when you\'re back in range.',
    },
  },

  // ── Auth (screens 03–04) ──────────────────────────────────
  auth: {
    phoneTitle: 'Enter your phone',
    phoneSubtitle: 'We\'ll send you a 6-digit code to sign in. International tourists and MBank users both welcome.',
    phonePlaceholder: 'Phone number',
    phoneHelper: 'We\'ll send you a verification code. Standard rates apply.',
    continueButton: 'Continue',
    orDivider: 'or',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    terms: 'By continuing you agree to our',
    termsLink: 'Terms',
    and: 'and',
    privacyLink: 'Privacy Policy',
    otpTitle: 'Check your messages',
    otpSubtitle: 'We sent a code to',
    otpResend: 'Didn\'t get it?',
    otpResendTimer: 'Resend in',
    otpResendNow: 'Resend now',
    otpVerify: 'Verify',
    otpChangeNumber: 'Change number',
    otpAutoFillTitle: 'Auto-fill from SMS',
    otpAutoFillBody: 'Tabylga will detect the code automatically when your SMS arrives.',
    demoHint: 'Demo: use code 000000',
    invalidCode: 'Invalid code. Use 000000 for the demo.',
    genericError: 'Something went wrong. Please try again.',
    otpCodeLabel: 'Enter 6-digit verification code',
  },

  // ── Home (screen 05) ─────────────────────────────────────
  home: {
    greeting: 'Hello, Traveler 👋',
    searchPlaceholder: 'Where are you going?',
    sectionRetreat: 'Countryside escapes this weekend',
    sectionTrending: 'Trending now',
    sectionServices: 'What are you looking for?',
    sectionAi: 'Plan with AI',
    aiCtaTitle: 'Plan my full trip with AI',
    aiCtaSubtitle: 'Answer 6 questions, get a complete itinerary in seconds.',
    aiCtaButton: 'Start planning',
    seeAll: 'See all',
    serviceHotels: 'Hotels',
    serviceHotelsSub: '324 places nearby',
    serviceFood: 'Food',
    serviceFoodSub: 'Dine in or delivery',
    serviceTransport: 'Transport',
    serviceTransportSub: 'Taxi, transfers, rent',
    serviceActivities: 'Activities',
    serviceActivitiesSub: 'Tours and guides',
    countrysideTag: 'Countryside',
    fromPrice: 'from',
    perNight: '/ night',
    notifications: 'Notifications',
    voiceSearch: 'Voice search',
  },

  // ── Map (screen 20) ──────────────────────────────────────
  map: {
    searchPlaceholder: 'Search on map…',
    filterAll: 'All',
    filterHotels: 'Hotels',
    filterFood: 'Food',
    filterActivities: 'Activities',
    filterNature: 'Nature',
    filterParks: 'Parks',
    filterRestPoints: 'Точки отдыха',
    filterAtms: 'ATMs',
    tapPinHint: 'Tap a pin to see details',
    loadingPlaces: 'Loading places…',
    placesFound: '{count} places',
    noPlaces: 'No places found for this filter.',
    useMyLocation: 'Use my location',
    locationUnavailable: 'Location is unavailable. Showing Kyrgyzstan overview.',
    openInMaps: 'Open in maps',
    distanceKm: '{km} km away',
    routeTitle: 'AI route on map',
    routeSubtitle: 'Stops are reordered from nearest to next point for easier driving.',
    openIn2gis: 'Open route in 2GIS',
    routePoints: 'Route points',
    routeMore: '+{count} more',
  },

  // ── Trips (screen 19) ────────────────────────────────────
  trips: {
    title: 'My Trips',
    emptyTitle: 'No trips yet',
    emptySubtitle: 'Plan your first trip with AI or browse our suggested itineraries.',
    emptyButton: 'Plan a trip',
    statusDraft: 'Draft',
    statusActive: 'Active',
    statusCompleted: 'Completed',
  },

  // ── Wallet (screens 21–23) ───────────────────────────────
  wallet: {
    title: 'My Wallet',
    balanceLabel: 'Available balance',
    statusOnline: 'Online',
    statusOfflineReady: 'Offline ready',
    statusReconnecting: 'Reconnecting…',
    topUp: 'Top up',
    pay: 'Pay',
    receive: 'Receive',
    historyTitle: 'Transactions',
    historyEmpty: 'No transactions yet.',
    topUpTitle: 'Top up wallet',
    payTitle: 'Scan to pay',
    scanPrompt: 'Point camera at a Tabylga or ELQR code',
    confirmTitle: 'Confirm payment',
    confirmButton: 'Pay now',
    offlineLimitLabel: 'Offline limit',
  },

  // ── Merchant (screens 24–25) ─────────────────────────────
  merchant: {
    title: 'Merchant Mode',
    dashboardTitle: 'My Business',
    acceptPayment: 'Accept Payment',
    amountPlaceholder: 'Enter amount (KGS)',
    showQrButton: 'Show QR Code',
    awaitingPayment: 'Waiting for customer scan…',
    paymentReceived: 'Payment received!',
    totalToday: 'Today\'s total',
    balanceLabel: 'Balance',
  },

  // ── Profile (screen 26) ──────────────────────────────────
  profile: {
    title: 'Profile',
    settingsSection: 'Settings',
    languageLabel: 'Language',
    merchantToggle: 'Switch to Merchant Mode',
    signOut: 'Sign out',
    reviewsTitle: 'My Reviews',
    reviewsEmpty: 'You haven\'t reviewed anything yet.',
  },

  // ── AI Planner (screens 14–18) ───────────────────────────
  planner: {
    stepPurposeQuestion: 'What brings you to Kyrgyzstan?',
    stepPurposeSubtitle: 'Pick what fits best — we\'ll tailor the trip around it.',
    stepCompanionsQuestion: 'Who are you traveling with?',
    stepDurationQuestion: 'How many days?',
    stepBudgetQuestion: 'What\'s your budget per person?',
    stepActivityQuestion: 'How active do you want to be?',
    stepInterestsQuestion: 'What interests you?',
    stepInterestsSubtitle: 'Pick all that apply.',
    stepDietaryQuestion: 'Any special requirements?',
    stepDietarySubtitle: 'Pick all that apply, or skip.',

    purposeLeisure: 'Leisure',
    purposeLeisureDesc: 'Slow days, beautiful views',
    purposeAdventure: 'Adventure',
    purposeAdventureDesc: 'Trekking, glaciers, peaks',
    purposeFamily: 'Family',
    purposeFamilyDesc: 'Kid-friendly stays',
    purposeBusiness: 'Business',
    purposeBusinessDesc: 'Bishkek, fast in/out',
    purposeRomantic: 'Romantic',
    purposeRomanticDesc: 'Lakes, yurts, sunsets',
    purposeCultural: 'Cultural',
    purposeCulturalDesc: 'History, crafts, music',
    purposeNomad: 'Digital Nomad',
    purposeNomadDesc: 'Wifi, cafés, long stays',
    purposePilgrimage: 'Pilgrimage',
    purposePilgrimageDesc: 'Sacred sites, reflection',

    companionSolo: 'Solo',
    companionCouple: 'Couple',
    companionFamily: 'Family',
    companionFriends: 'Friends',
    companionColleagues: 'Colleagues',
    groupSize: 'Group size',
    kidsAges: 'Kids ages 5–12 years',
    decreaseGroupSize: 'Decrease group size',
    increaseGroupSize: 'Increase group size',

    activityChill: 'Chill',
    activityChillDesc: 'Cafés, views, easy walks',
    activityModerate: 'Moderate',
    activityModerateDesc: 'Some hiking, sightseeing',
    activityActive: 'Active',
    activityActiveDesc: 'Daily hikes, horse riding',
    activityExtreme: 'Extreme',
    activityExtremeDesc: 'Glaciers, peaks, multi-day',

    interestNature: 'Nature',
    interestCulture: 'Culture',
    interestFood: 'Food',
    interestExtreme: 'Extreme sports',
    interestPhoto: 'Photography',
    interestShopping: 'Shopping',
    interestWellness: 'Wellness',
    interestNightlife: 'Nightlife',

    dietaryVegetarian: 'Vegetarian',
    dietaryHalal: 'Halal',
    dietaryVegan: 'Vegan',
    dietaryWheelchair: 'Wheelchair',
    dietaryFamily: 'Family-friendly',
    dietaryNone: 'None',

    days3: '3 days',
    days5: '5 days',
    days7: '7 days',
    days10: '10 days',
    days14: '14+ days',

    budget100: '$100–300',
    budget300: '$300–600',
    budget600: '$600–1200',
    budget1200: '$1200+',

    progressLabel: 'Step {current} of {total}',
    backButton: 'Back',
    nextButton: 'Next',
    generateButton: 'Generate my trip ✨',

    discardTitle: 'Discard trip?',
    discardMessage: 'Your answers won\'t be saved.',
    discardConfirm: 'Discard',
    discardCancel: 'Keep planning',

    generatingTitle: 'Building your perfect trip',
    genStep1: 'Analyzing 847 places…',
    genStep2: 'Matching your interests…',
    genStep3: 'Optimizing logistics…',
    genStep4: 'Balancing regions…',
    genStep5: 'Ready!',
    generatingError: 'AI couldn\'t finish this trip.',
    generatingRetry: 'Try again',

    voiceTitle: 'Tell me about your trip',
    voiceHint: 'Hold to speak',
    voiceTranscribing: 'Listening…',
    collaborateTitle: 'Plan together',
    collaborateSubtitle: 'Invite friends to add their preferences.',
    inviteButton: 'Invite by phone',
  },

  // ── Itinerary (screen 19) ────────────────────────────────
  itinerary: {
    headerTitle: 'Your trip',
    metaTravelers: '{count} travelers',
    metaActivity: 'Moderate',
    totalLabel: 'Total',
    payCta: 'Pay & lock itinerary',
    dayLabel: 'Day {n}',
    aiInsightTitle: 'AI suggestion',
    aiInsightExample: 'Add horseback riding on Day 3? +$25',
    aiInsightAdd: 'Add',
    tipsTitle: 'Tips for this trip',
    noItinerary: 'No itinerary loaded.',
    backHome: 'Back to home',
    shareTrip: 'Share trip',
    traveler: 'traveler',
    travelers: 'travelers',
    regions: '{count} regions',
    daysCount: '{count} days',
    free: 'Free',
  },

  // ── Services ─────────────────────────────────────────────
  services: {
    hotelsTitle: 'Hotels',
    foodTitle: 'Food',
    transportTitle: 'Transport',
    activitiesTitle: 'Activities',
    listView: 'List',
    mapView: 'Map',
    book: 'Book',
    limitedAvailability: 'Limited availability',
    filterAll: 'All',
    filterPrice: 'Price',
    filterRating: 'Rating',
    filterHotel: 'Hotel',
    filterHostel: 'Hostel',
    filterYurt: 'Yurt',
    filterGuesthouse: 'Guesthouse',
    tabRestaurants: 'Restaurants',
    tabCafes: 'Cafes',
    tabDelivery: 'Delivery',
    tabTaxi: 'Taxi',
    tabTransfers: 'Transfers',
    tabRent: 'Rent',
    economy: 'Economy',
    comfort: 'Comfort',
    minivan: 'Minivan',
    duration: 'Duration',
    difficulty: 'Difficulty',
    groupSize: 'Group size',
    perPerson: '/ person',
    stars: '{n} stars',
    open: 'Open',
    closed: 'Closed',
    setPickupLocation: 'Set pickup location',
    seats: '{count} seats',
    intercityComingSoon: 'Intercity transfers coming soon',
    rentalsComingSoon: 'Car rentals coming soon',
  },

  // ── Wallet extras ─────────────────────────────────────────
  walletExtra: {
    statusOnline: '🟢 Online',
    statusOffline: '🟡 Offline ready',
    balance: 'Balance',
    approxKgs: '≈ {kgs} KGS',
    rateLink: 'Rate: 87.00 KGS/USD',
    actionTopUp: 'Top up',
    actionPay: 'Pay',
    actionReceive: 'Receive',
    recentTitle: 'Recent transactions',
    topUpTitle: 'Top up wallet',
    amountLabel: 'Amount',
    convertedKgs: '= {kgs} KGS at {rate} rate',
    methodMBank: 'MBank',
    methodMBankSub: 'Instant, no fees',
    methodMBankBadge: 'Recommended',
    methodCard: 'Credit or debit card',
    methodApplePay: 'Apple Pay / Google Pay',
    securedBy: '🔒 Secured by KICB',
    payCtaLabel: 'Pay {amount}',
    cardNumber: 'Card number',
    expiry: 'MM / YY',
    cvc: 'CVC',
    scanTitle: 'Scan to pay',
    scanInstruction: 'Scan merchant\'s QR code',
    cantScan: 'Can\'t scan? Enter merchant ID',
    confirmTitle: 'Ready to pay',
    confirmPay: 'Pay now',
    receiveTitle: 'My QR code',
    receiveSubtitle: 'Show this to receive payment',
    traveler: 'Traveler',
    shareQr: 'Share',
    saveQr: 'Save image',
    toggleOffline: 'Toggle offline',
    offlineBanner: 'You\'re offline — wallet works for {amount} more',
    offlineStatus: 'Offline ready · {amount} available',
    lastSynced: 'Last synced 2 hours ago',
    offlineHint: 'Pay offline with up to {amount} · syncs automatically when back online',
    pendingSync: 'Pending sync',
    processingPayment: 'Processing payment…',
    topUpSuccess: '${amount} added!',
    paymentMethod: 'Payment method',
    convertedRate: '= {kgs} KGS at {rate} rate',
    payAmount: 'Pay ${amount}',
    paymentSent: 'Payment sent!',
  },

  // ── Merchant extras ───────────────────────────────────────
  merchantExtra: {
    modeTraverler: 'Traveler',
    modeMerchant: 'Merchant',
    verified: 'Verified',
    earningsToday: 'Earnings today',
    transactionsCount: '{n} transactions',
    avgTransaction: 'Avg {amount}',
    acceptCta: 'Accept payment',
    withdrawCta: 'Withdraw to card ••1234',
    acceptTitle: 'Accept payment',
    toggleKgs: 'KGS',
    toggleUsd: 'USD',
    generateQr: 'Generate QR',
    showToCustomer: 'Show to customer',
    expiresIn: 'Expires in {time}',
    cancelPayment: 'Cancel',
    addNote: 'Add note (optional)',
    thisWeek: 'This week',
    recentPayments: 'Recent payments',
    reviewsCount: '({count} reviews)',
  },

  // ── Voice ─────────────────────────────────────────────────
  voice: {
    listening: 'Listening...',
    hint: 'Speak naturally about your trip',
    switchKeyboard: 'Switch to quiz',
  },

  // ── Profile extras ────────────────────────────────────────
  profileExtra: {
    tripsShortcut: 'My trips',
    tripsCount: '{upcoming} upcoming, {past} past',
    settingsLanguage: 'Language',
    settingsEsim: 'Travel eSIM',
    settingsTranslator: 'Translator',
    settingsPayment: 'Payment methods',
    settingsNotifications: 'Notifications',
    settingsSecurity: 'Security',
    settingsRatings: 'Rating history',
    settingsCollaborative: 'Collaborative trips',
    settingsReferrals: 'Referrals',
    settingsHelp: 'Help',
    settingsAbout: 'About',
    settingsPrivacy: 'Privacy',
    settingsMerchant: 'Switch to Merchant Mode',
    version: 'Tabylga v1.0.0',
    languagePickerTitle: 'App language',
    currentLanguage: 'Current: {language}',
  },

  tabs: {
    home: 'Home',
    map: 'Map',
    trips: 'Trips',
    wallet: 'Wallet',
    profile: 'Profile',
  },

  rating: {
    targetName: 'Nomad\'s Yurt Camp',
    targetRegion: 'Song-Kul, Naryn region',
    title: 'How was your stay?',
    tapToRate: 'Tap to rate',
    cleanliness: 'Cleanliness',
    staff: 'Staff',
    location: 'Location',
    value: 'Value for money',
    reviewPlaceholder: 'Share details of your experience (optional)',
    addPhotos: 'Add up to 3 photos',
    submit: 'Submit review',
    maybeLater: 'Maybe later',
  },

  esim: {
    title: 'Stay connected in Kyrgyzstan',
    subtitle: 'Choose a temporary eSIM now or return to this from Profile anytime.',
    need: 'Get eSIM',
    later: 'Later',
    skip: 'No eSIM needed',
    recommended: 'Recommended',
    activeChoice: 'Selected: {plan}',
    days: '{count} days',
    data: '{count} GB',
  },

  preferences: {
    title: 'Trip basics',
    subtitle: 'This helps us estimate transport and split route deposits correctly.',
    peopleCount: 'How many people travel with you?',
    preferredTourPeople: 'How many people do you want in a shared tour?',
    age: 'Your age',
    strangerMatch: 'Find compatible travelers',
    transportDeposit: 'Transport deposit is calculated per person for round trip only.',
    enabled: 'ON',
    disabled: 'OFF',
  },

  taxi: {
    title: 'Taxi and tour transport',
    pickup: 'Pickup',
    dropoff: 'Drop-off',
    pickupPlaceholder: 'Manas Airport',
    dropoffPlaceholder: 'Hotel or place',
    order: 'Order taxi',
    ordering: 'Finding driver…',
    arriving: '{driver} arrives in {minutes} min',
    routePreview: 'Route preview',
    reviewsTitle: 'Driver reviews',
    sharedTourTitle: 'Bus / minivan for tours',
    peopleWant: '{count} people requested',
    reserveSeat: 'Reserve round-trip seat',
    depositPerPerson: 'Road deposit per person',
  },

  bluetoothPay: {
    title: 'Bluetooth offline pay',
    subtitle: 'Demo flow like MBank offline: both devices sign locally, then sync later.',
    nearby: 'Nearby merchants',
    scanning: 'Scanning Bluetooth nearby…',
    sign: 'Sign offline payment',
    signed: 'Payment signed offline',
    syncLater: 'It will settle when either device returns online.',
  },

  groupPlanner: {
    title: 'Plan with compatible travelers',
    subtitle: 'AI matches age range and interests, suggests a meetup, and opens a group chat.',
    overlap: '{score}% overlap',
    suggestedMeetup: 'Suggested meetup',
    createChat: 'Create group chat',
    chatTitle: 'Shared trip chat',
    transportSplit: 'Split transport for one person first',
  },

  translator: {
    title: 'Travel translator',
    subtitle: 'Text-to-text demo with voice playback placeholder.',
    inputPlaceholder: 'Type or paste a phrase',
    targetLanguage: 'Target language',
    translate: 'Translate',
    readAloud: 'Read translation aloud',
    listening: 'Voice input demo',
    output: 'Translation',
  },

  // ── Shared / Global ──────────────────────────────────────
  common: {
    back: 'Back',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    confirm: 'Confirm',
    loading: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Try again',
    noResults: 'No results found.',
    bookNow: 'Book now',
    viewDetails: 'View details',
    perNight: '/ night',
    perPerson: '/ person',
    rating: 'Rating',
    reviews: 'reviews',
    from: 'From',
    usd: 'USD',
    kgs: 'KGS',
  },

  // ── States ───────────────────────────────────────────────
  states: {
    offline: 'You\'re offline',
    offlineSubtitle: 'Your wallet is ready for offline payments.',
    empty: 'Nothing here yet',
    errorTitle: 'Something went wrong',
    errorButton: 'Try again',
  },
} as const;

type WidenStrings<T> = T extends string
  ? string
  : T extends Record<string, unknown>
    ? { [K in keyof T]: WidenStrings<T[K]> }
    : T;

export type Strings = WidenStrings<typeof enStrings>;
type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends Record<string, unknown> ? DeepPartial<T[K]> : T[K];
};

const ruStrings = {
  splash: {
    tagline: 'Весь Кыргызстан в одном касании',
    taglineSub: 'Найди · Планируй · Табыл',
    languageSheetTitle: 'Выберите язык',
    continueButton: 'Продолжить',
  },
  welcome: {
    skip: 'Пропустить',
    next: 'Далее',
    getStarted: 'Начать',
    slide1: {
      title: 'Планируйте с AI или самостоятельно.',
      body: 'Создайте маршрут на несколько дней из одной фразы или бронируйте отели, такси и гидов вручную — все в одном приложении.',
    },
    slide2: {
      title: 'Один кошелек для всей поездки.',
      body: 'Пополните один раз через Visa, MBank, UnionPay или Apple Pay. Платите в юрточных лагерях, ресторанах и у гидов без наличных.',
    },
    slide3: {
      title: 'Работает даже офлайн в горах.',
      body: 'Нет связи? Не проблема. Оплатите проживание на Сон-Куле подписанным офлайн-токеном. Синхронизация пройдет, когда связь вернется.',
    },
  },
  auth: {
    phoneTitle: 'Введите телефон',
    phoneSubtitle: 'Мы отправим 6-значный код для входа. Подходит туристам из других стран и пользователям MBank.',
    phonePlaceholder: 'Номер телефона',
    phoneHelper: 'Мы отправим код подтверждения. Возможна стандартная плата оператора.',
    continueButton: 'Продолжить',
    orDivider: 'или',
    continueGoogle: 'Продолжить с Google',
    continueApple: 'Продолжить с Apple',
    terms: 'Продолжая, вы соглашаетесь с',
    termsLink: 'Условиями',
    and: 'и',
    privacyLink: 'Политикой конфиденциальности',
    otpTitle: 'Проверьте сообщения',
    otpSubtitle: 'Мы отправили код на',
    otpResend: 'Код не пришел?',
    otpResendTimer: 'Повторно через',
    otpResendNow: 'Отправить снова',
    otpVerify: 'Подтвердить',
    otpChangeNumber: 'Изменить номер',
    otpAutoFillTitle: 'Автозаполнение из SMS',
    otpAutoFillBody: 'Tabylga автоматически распознает код, когда SMS придет.',
    demoHint: 'Демо: используйте код 000000',
    invalidCode: 'Неверный код. Для демо используйте 000000.',
    genericError: 'Что-то пошло не так. Попробуйте еще раз.',
    otpCodeLabel: 'Введите 6-значный код подтверждения',
  },
  home: {
    greeting: 'Здравствуйте, путешественник',
    searchPlaceholder: 'Куда вы едете?',
    sectionRetreat: 'Загородные поездки на выходные',
    sectionTrending: 'Сейчас популярно',
    sectionServices: 'Что вы ищете?',
    sectionAi: 'Планирование с AI',
    aiCtaTitle: 'Спланировать всю поездку с AI',
    aiCtaSubtitle: 'Ответьте на 6 вопросов и получите маршрут за секунды.',
    aiCtaButton: 'Начать планирование',
    seeAll: 'Все',
    serviceHotels: 'Отели',
    serviceHotelsSub: '324 места рядом',
    serviceFood: 'Еда',
    serviceFoodSub: 'Рестораны и доставка',
    serviceTransport: 'Транспорт',
    serviceTransportSub: 'Такси, трансферы, аренда',
    serviceActivities: 'Активности',
    serviceActivitiesSub: 'Туры и гиды',
    countrysideTag: 'За городом',
    fromPrice: 'от',
    perNight: '/ ночь',
    notifications: 'Уведомления',
    voiceSearch: 'Голосовой поиск',
  },
  map: {
    searchPlaceholder: 'Поиск на карте…',
    filterAll: 'Все',
    filterHotels: 'Отели',
    filterFood: 'Еда',
    filterActivities: 'Активности',
    filterNature: 'Природа',
    filterParks: 'Парки',
    filterRestPoints: 'Rest Points',
    filterAtms: 'Банкоматы',
    tapPinHint: 'Нажмите на метку, чтобы увидеть детали',
    loadingPlaces: 'Загружаем места…',
    placesFound: '{count} мест',
    noPlaces: 'По этому фильтру мест не найдено.',
    useMyLocation: 'Моя геолокация',
    locationUnavailable: 'Геолокация недоступна. Показываем обзор Кыргызстана.',
    openInMaps: 'Открыть в картах',
    distanceKm: '{km} км от вас',
    routeTitle: 'AI-маршрут на карте',
    routeSubtitle: 'Точки отсортированы от ближайшей к следующей, чтобы ехать логичнее.',
    openIn2gis: 'Открыть маршрут в 2GIS',
    routePoints: 'Точки маршрута',
    routeMore: '+{count} еще',
  },
  trips: {
    title: 'Мои поездки',
    emptyTitle: 'Поездок пока нет',
    emptySubtitle: 'Спланируйте первую поездку с AI или посмотрите готовые маршруты.',
    emptyButton: 'Спланировать поездку',
    statusDraft: 'Черновик',
    statusActive: 'Активная',
    statusCompleted: 'Завершена',
  },
  wallet: {
    title: 'Мой кошелек',
    balanceLabel: 'Доступный баланс',
    statusOnline: 'Онлайн',
    statusOfflineReady: 'Офлайн готов',
    statusReconnecting: 'Переподключение…',
    topUp: 'Пополнить',
    pay: 'Оплатить',
    receive: 'Получить',
    historyTitle: 'Транзакции',
    historyEmpty: 'Транзакций пока нет.',
    topUpTitle: 'Пополнить кошелек',
    payTitle: 'Оплата по QR',
    scanPrompt: 'Наведи камеру на Tabylga или ELQR код',
    confirmTitle: 'Подтвердите оплату',
    confirmButton: 'Оплатить',
    offlineLimitLabel: 'Офлайн лимит',
  },
  merchant: {
    title: 'Режим мерчанта',
    dashboardTitle: 'Мой бизнес',
    acceptPayment: 'Принять оплату',
    amountPlaceholder: 'Введите сумму (KGS)',
    showQrButton: 'Показать QR-код',
    awaitingPayment: 'Ждем сканирования клиентом…',
    paymentReceived: 'Оплата получена!',
    totalToday: 'Итого сегодня',
    balanceLabel: 'Баланс',
  },
  profile: {
    title: 'Профиль',
    settingsSection: 'Настройки',
    languageLabel: 'Язык',
    merchantToggle: 'Перейти в режим мерчанта',
    signOut: 'Выйти',
    reviewsTitle: 'Мои отзывы',
    reviewsEmpty: 'Вы пока ничего не оценивали.',
  },
  planner: {
    stepPurposeQuestion: 'Зачем вы едете в Кыргызстан?',
    stepPurposeSubtitle: 'Выберите подходящий вариант — мы подстроим маршрут.',
    stepCompanionsQuestion: 'С кем вы путешествуете?',
    stepDurationQuestion: 'На сколько дней?',
    stepBudgetQuestion: 'Какой бюджет на человека?',
    stepActivityQuestion: 'Какой темп поездки вам подходит?',
    stepInterestsQuestion: 'Что вам интересно?',
    stepInterestsSubtitle: 'Можно выбрать несколько вариантов.',
    stepDietaryQuestion: 'Есть особые требования?',
    stepDietarySubtitle: 'Выберите нужное или пропустите.',
    purposeLeisure: 'Отдых',
    purposeLeisureDesc: 'Спокойные дни и виды',
    purposeAdventure: 'Приключения',
    purposeAdventureDesc: 'Трекинги, ледники, вершины',
    purposeFamily: 'Семья',
    purposeFamilyDesc: 'Удобно для детей',
    purposeBusiness: 'Бизнес',
    purposeBusinessDesc: 'Бишкек, быстро и удобно',
    purposeRomantic: 'Романтика',
    purposeRomanticDesc: 'Озера, юрты, закаты',
    purposeCultural: 'Культура',
    purposeCulturalDesc: 'История, ремесла, музыка',
    purposeNomad: 'Digital Nomad',
    purposeNomadDesc: 'Wi-Fi, кафе, долгий stay',
    purposePilgrimage: 'Паломничество',
    purposePilgrimageDesc: 'Святые места и тишина',
    companionSolo: 'Один',
    companionCouple: 'Пара',
    companionFamily: 'Семья',
    companionFriends: 'Друзья',
    companionColleagues: 'Коллеги',
    groupSize: 'Размер группы',
    kidsAges: 'Возраст детей 5–12 лет',
    decreaseGroupSize: 'Уменьшить размер группы',
    increaseGroupSize: 'Увеличить размер группы',
    activityChill: 'Спокойно',
    activityChillDesc: 'Кафе, виды, легкие прогулки',
    activityModerate: 'Средне',
    activityModerateDesc: 'Немного хайкинга и прогулок',
    activityActive: 'Активно',
    activityActiveDesc: 'Хайкинг и конные прогулки каждый день',
    activityExtreme: 'Экстрим',
    activityExtremeDesc: 'Ледники, вершины, многодневные маршруты',
    interestNature: 'Природа',
    interestCulture: 'Культура',
    interestFood: 'Еда',
    interestExtreme: 'Экстрим',
    interestPhoto: 'Фотография',
    interestShopping: 'Шопинг',
    interestWellness: 'Wellness',
    interestNightlife: 'Ночная жизнь',
    dietaryVegetarian: 'Вегетарианское',
    dietaryHalal: 'Халал',
    dietaryVegan: 'Веганское',
    dietaryWheelchair: 'Доступная среда',
    dietaryFamily: 'Для семьи',
    dietaryNone: 'Нет',
    days3: '3 дня',
    days5: '5 дней',
    days7: '7 дней',
    days10: '10 дней',
    days14: '14+ дней',
    progressLabel: 'Шаг {current} из {total}',
    backButton: 'Назад',
    nextButton: 'Далее',
    generateButton: 'Создать маршрут',
    discardTitle: 'Сбросить маршрут?',
    discardMessage: 'Ваши ответы не будут сохранены.',
    discardConfirm: 'Сбросить',
    discardCancel: 'Продолжить',
    generatingTitle: 'Собираем идеальный маршрут',
    genStep1: 'Анализируем 847 мест…',
    genStep2: 'Сопоставляем интересы…',
    genStep3: 'Оптимизируем логистику…',
    genStep4: 'Балансируем регионы…',
    genStep5: 'Готово!',
    generatingError: 'AI не смог завершить маршрут.',
    generatingRetry: 'Попробовать снова',
    voiceTitle: 'Расскажите о поездке',
    voiceHint: 'Удерживайте, чтобы говорить',
    voiceTranscribing: 'Слушаем…',
    collaborateTitle: 'Планировать вместе',
    collaborateSubtitle: 'Пригласите друзей добавить предпочтения.',
    inviteButton: 'Пригласить по телефону',
  },
  itinerary: {
    headerTitle: 'Ваш маршрут',
    metaTravelers: '{count} путешественников',
    metaActivity: 'Средний темп',
    totalLabel: 'Итого',
    payCta: 'Оплатить и закрепить маршрут',
    dayLabel: 'День {n}',
    aiInsightTitle: 'Совет AI',
    aiInsightExample: 'Добавить конную прогулку в День 3? +$25',
    aiInsightAdd: 'Добавить',
    tipsTitle: 'Советы для поездки',
    noItinerary: 'Маршрут не загружен.',
    backHome: 'На главную',
    shareTrip: 'Поделиться маршрутом',
    traveler: 'путешественник',
    travelers: 'путешественников',
    regions: '{count} регионов',
    daysCount: '{count} дней',
    free: 'Бесплатно',
  },
  services: {
    hotelsTitle: 'Отели',
    foodTitle: 'Еда',
    transportTitle: 'Транспорт',
    activitiesTitle: 'Активности',
    listView: 'Список',
    mapView: 'Карта',
    book: 'Бронь',
    limitedAvailability: 'Мало мест',
    filterAll: 'Все',
    filterPrice: 'Цена',
    filterRating: 'Рейтинг',
    filterHotel: 'Отель',
    filterHostel: 'Хостел',
    filterYurt: 'Юрта',
    filterGuesthouse: 'Гостевой дом',
    tabRestaurants: 'Рестораны',
    tabCafes: 'Кафе',
    tabDelivery: 'Доставка',
    tabTaxi: 'Такси',
    tabTransfers: 'Трансферы',
    tabRent: 'Аренда',
    economy: 'Эконом',
    comfort: 'Комфорт',
    minivan: 'Минивэн',
    duration: 'Длительность',
    difficulty: 'Сложность',
    groupSize: 'Размер группы',
    perPerson: '/ человек',
    stars: '{n} звезд',
    open: 'Открыто',
    closed: 'Закрыто',
    setPickupLocation: 'Укажите место посадки',
    seats: '{count} мест',
    intercityComingSoon: 'Междугородние трансферы скоро',
    rentalsComingSoon: 'Аренда авто скоро',
  },
  walletExtra: {
    statusOnline: 'Онлайн',
    statusOffline: 'Офлайн готов',
    balance: 'Баланс',
    approxKgs: '≈ {kgs} KGS',
    rateLink: 'Курс: 87.00 KGS/USD',
    actionTopUp: 'Пополнить',
    actionPay: 'Оплатить',
    actionReceive: 'Получить',
    recentTitle: 'Последние транзакции',
    topUpTitle: 'Пополнить кошелек',
    amountLabel: 'Сумма',
    convertedKgs: '= {kgs} KGS по курсу {rate}',
    methodMBank: 'MBank',
    methodMBankSub: 'Мгновенно, без комиссии',
    methodMBankBadge: 'Рекомендуем',
    methodCard: 'Кредитная или дебетовая карта',
    methodApplePay: 'Apple Pay / Google Pay',
    securedBy: 'Защищено KICB',
    payCtaLabel: 'Оплатить {amount}',
    cardNumber: 'Номер карты',
    expiry: 'ММ / ГГ',
    cvc: 'CVC',
    scanTitle: 'Оплата по QR',
    scanInstruction: 'Сканируйте QR-код мерчанта',
    cantScan: 'Не сканируется? Введите ID мерчанта',
    confirmTitle: 'Готово к оплате',
    confirmPay: 'Оплатить',
    receiveTitle: 'Мой QR-код',
    receiveSubtitle: 'Покажите этот код, чтобы получить оплату',
    traveler: 'Путешественник',
    shareQr: 'Поделиться',
    saveQr: 'Сохранить',
    toggleOffline: 'Переключить офлайн',
    offlineBanner: 'Вы офлайн — кошелек работает еще на {amount}',
    offlineStatus: 'Офлайн готов · доступно {amount}',
    lastSynced: 'Последняя синхронизация 2 часа назад',
    offlineHint: 'Платите офлайн до {amount} · синхронизация пройдет при появлении сети',
    pendingSync: 'Ожидает синхронизации',
    processingPayment: 'Обрабатываем платеж…',
    topUpSuccess: '${amount} добавлено!',
    paymentMethod: 'Способ оплаты',
    convertedRate: '= {kgs} KGS по курсу {rate}',
    payAmount: 'Оплатить ${amount}',
    paymentSent: 'Платеж отправлен!',
  },
  merchantExtra: {
    modeTraverler: 'Турист',
    modeMerchant: 'Мерчант',
    verified: 'Проверено',
    earningsToday: 'Выручка сегодня',
    transactionsCount: '{n} транзакций',
    avgTransaction: 'Средний чек {amount}',
    acceptCta: 'Принять оплату',
    withdrawCta: 'Вывести на карту ••1234',
    acceptTitle: 'Принять оплату',
    generateQr: 'Создать QR',
    showToCustomer: 'Покажите клиенту',
    expiresIn: 'Истекает через {time}',
    cancelPayment: 'Отменить',
    addNote: 'Добавить заметку (необязательно)',
    thisWeek: 'Эта неделя',
    recentPayments: 'Последние оплаты',
    reviewsCount: '({count} отзывов)',
  },
  voice: {
    listening: 'Слушаем...',
    hint: 'Расскажите о поездке естественным языком',
    switchKeyboard: 'Перейти к анкете',
  },
  profileExtra: {
    tripsShortcut: 'Мои поездки',
    tripsCount: '{upcoming} будущих, {past} прошлых',
    settingsLanguage: 'Язык',
    settingsEsim: 'Туристическая eSIM',
    settingsTranslator: 'Переводчик',
    settingsPayment: 'Способы оплаты',
    settingsNotifications: 'Уведомления',
    settingsSecurity: 'Безопасность',
    settingsRatings: 'История оценок',
    settingsCollaborative: 'Совместные поездки',
    settingsReferrals: 'Рефералы',
    settingsHelp: 'Помощь',
    settingsAbout: 'О приложении',
    settingsPrivacy: 'Конфиденциальность',
    settingsMerchant: 'Перейти в режим мерчанта',
    languagePickerTitle: 'Язык приложения',
    currentLanguage: 'Сейчас: {language}',
  },
  tabs: {
    home: 'Главная',
    map: 'Карта',
    trips: 'Поездки',
    wallet: 'Кошелек',
    profile: 'Профиль',
  },
  rating: {
    targetRegion: 'Сон-Куль, Нарынская область',
    title: 'Как прошло проживание?',
    tapToRate: 'Нажмите для оценки',
    cleanliness: 'Чистота',
    staff: 'Персонал',
    location: 'Локация',
    value: 'Цена/качество',
    reviewPlaceholder: 'Расскажите подробнее о впечатлениях (необязательно)',
    addPhotos: 'Добавьте до 3 фото',
    submit: 'Отправить отзыв',
    maybeLater: 'Позже',
  },

  esim: {
    title: 'Оставайтесь на связи в Кыргызстане',
    subtitle: 'Выберите временную eSIM сейчас или вернитесь к этому из профиля.',
    need: 'Подключить eSIM',
    later: 'Позже',
    skip: 'eSIM не нужна',
    recommended: 'Рекомендуем',
    activeChoice: 'Выбрано: {plan}',
    days: '{count} дней',
    data: '{count} ГБ',
  },

  preferences: {
    title: 'Базовые данные поездки',
    subtitle: 'Так мы точнее считаем транспорт и депозит за маршрут.',
    peopleCount: 'Сколько людей едет с вами?',
    preferredTourPeople: 'Сколько людей вы хотите в общем туре?',
    age: 'Ваш возраст',
    strangerMatch: 'Подобрать попутчиков',
    transportDeposit: 'Депозит за транспорт считается за одного человека туда и обратно.',
    enabled: 'ВКЛ',
    disabled: 'ВЫКЛ',
  },

  taxi: {
    title: 'Такси и тур-транспорт',
    pickup: 'Откуда',
    dropoff: 'Куда',
    pickupPlaceholder: 'Аэропорт Манас',
    dropoffPlaceholder: 'Отель или место',
    order: 'Заказать такси',
    ordering: 'Ищем водителя…',
    arriving: '{driver} будет через {minutes} мин',
    routePreview: 'Предпросмотр маршрута',
    reviewsTitle: 'Отзывы о водителе',
    sharedTourTitle: 'Бус / минивэн для тура',
    peopleWant: 'Запрошено людей: {count}',
    reserveSeat: 'Забронировать место туда-обратно',
    depositPerPerson: 'Депозит за дорогу на человека',
  },

  bluetoothPay: {
    title: 'Офлайн-оплата по Bluetooth',
    subtitle: 'Демо как в MBank offline: оба устройства подписывают платеж локально, потом синхронизируют.',
    nearby: 'Мерчанты рядом',
    scanning: 'Ищем устройства по Bluetooth…',
    sign: 'Подписать офлайн-платеж',
    signed: 'Платеж подписан офлайн',
    syncLater: 'Он проведется, когда одно из устройств вернется онлайн.',
  },

  groupPlanner: {
    title: 'План с подходящими попутчиками',
    subtitle: 'AI сопоставляет возраст и интересы, предлагает встречу и открывает общий чат.',
    overlap: 'Совпадение {score}%',
    suggestedMeetup: 'Предложение для встречи',
    createChat: 'Создать общий чат',
    chatTitle: 'Чат общей поездки',
    transportSplit: 'Сначала разделить транспорт за 1 человека',
  },

  translator: {
    title: 'Туристический переводчик',
    subtitle: 'Демо текстового перевода с имитацией голосового чтения.',
    inputPlaceholder: 'Введите или вставьте фразу',
    targetLanguage: 'Язык перевода',
    translate: 'Перевести',
    readAloud: 'Прочитать перевод',
    listening: 'Демо голосового ввода',
    output: 'Перевод',
  },
  common: {
    back: 'Назад',
    close: 'Закрыть',
    cancel: 'Отмена',
    save: 'Сохранить',
    confirm: 'Подтвердить',
    loading: 'Загрузка…',
    error: 'Что-то пошло не так.',
    retry: 'Попробовать снова',
    noResults: 'Ничего не найдено.',
    bookNow: 'Забронировать',
    viewDetails: 'Подробнее',
    perNight: '/ ночь',
    perPerson: '/ человек',
    rating: 'Рейтинг',
    reviews: 'отзывов',
    from: 'От',
  },
  states: {
    offline: 'Вы офлайн',
    offlineSubtitle: 'Кошелек готов к офлайн-платежам.',
    empty: 'Здесь пока пусто',
    errorTitle: 'Что-то пошло не так',
    errorButton: 'Попробовать снова',
  },
} satisfies DeepPartial<Strings>;

const localeOverlays: Partial<Record<Language, DeepPartial<Strings>>> = {
  ru: ruStrings,
};

function isObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function mergeStrings<T>(base: T, overlay?: DeepPartial<T>): T {
  if (!overlay || !isObject(base) || !isObject(overlay)) return base;
  const merged: Record<string, unknown> = { ...base };
  for (const key of Object.keys(overlay) as Array<keyof T & string>) {
    const nextOverlay = overlay[key];
    const baseValue = (base as Record<string, unknown>)[key];
    merged[key] = isObject(baseValue) && isObject(nextOverlay)
      ? mergeStrings(baseValue, nextOverlay as DeepPartial<typeof baseValue>)
      : nextOverlay ?? baseValue;
  }
  return merged as T;
}

export function getStrings(language: Language): Strings {
  return mergeStrings(enStrings, localeOverlays[language]);
}

export function formatString(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (result, [key, value]) =>
      result
        .replace(new RegExp(`\\{${key}\\}`, 'g'), String(value))
        .replace(new RegExp(`\\$\\{${key}\\}`, 'g'), String(value)),
    template
  );
}

export const LANGUAGE_OPTIONS: Array<{
  code: Language;
  label: string;
  native: string;
  flag: string;
}> = [
  { code: 'en', label: 'English', native: 'English', flag: 'GB' },
  { code: 'ru', label: 'Russian', native: 'Русский', flag: 'RU' },
  { code: 'ky', label: 'Kyrgyz', native: 'Кыргызча', flag: 'KG' },
  { code: 'zh', label: 'Chinese', native: '中文', flag: 'CN' },
  { code: 'ar', label: 'Arabic', native: 'العربية', flag: 'SA' },
  { code: 'de', label: 'German', native: 'Deutsch', flag: 'DE' },
];

export const strings = enStrings;
